### ISSUE TITLE
Rush add -p is does not see local package

### ISSUE THREAD

**Issue by Jabher** [microsoft/rushstack#1469] opened 2019-08-19 08:16 UTC
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

1. I creates empty rush monorepo
2. I add 2 separate packages (`a`,`b`) without publishing any of them
3. I run `rush add -p b` in package `a`
4. I encounter the following error
```
jabher-osx:<PATH> jabher$ rush add -p <B>
Your version of Node.js (12.8.1) has not been tested with this release of Rush. The Rush team will not accept issue reports for it. Please consider upgrading Rush or downgrading Node.js.
Found configuration in <PATH>/rush.json


Rush Multi-Project Build Tool 5.9.1 - https://rushjs.io

Found configuration in <PATH>/rush.json

Starting "rush add"

Determining new version for dependency: <B>
No version selector was specified, so the version will be determined automatically.

The "ensureConsistentVersions" policy is NOT active, so we will assign the latest version.

Querying NPM registry for latest version of "<B>"...

ERROR: The command failed with exit code 1
npm ERR! code E404
npm ERR! 404 '<B>' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404 
npm ERR! 404  '<B>@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     <$PATH>/.npm/_logs/2019-08-19T08_12_51_250Z-debug.log
```

**What is the expected behavior?**
local package is discovered

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 
5.9.1
* **Node Version:** 
v12.8.1
  * **Is this a LTS version?** 
No
  * **Have you tested on a LTS version?** 
No
* **OS:** 
Mac OS X 10.14.6

**Comment by halfnibble** [comment] 2019-08-19 16:21
Is project b listed in your rush.json file under projects?

**Comment by iclanton** [comment] 2019-08-19 17:40
I'm seeing this issue too. I suspect this is a regression.

**Comment by halfnibble** [comment] 2019-08-19 18:25
I have a minimal repro handy.
https://github.com/halfnibble/newmono

Reproduce with
`$ cd apps/projectA`
`$ rush add project-b`

**Comment by halfnibble** [comment] 2019-08-19 18:39
Ah ha! I figured out why it was working for me earlier. Apparently, it works if the folder name is the same as the project name—or doesn't contain special characters. Or at least it does in this minimal repro of rush add -p working:
https://github.com/halfnibble/newmono_working

Reproduce with
`$ cd apps/projecta`
`$ rush add -p projectb`

**Comment by VincentSurelle** [comment] 2019-10-22 13:35
@halfnibble Oh great, I understand now why I'm having troubles with local dependencies.
It never worked for me but I think that's because I'm using private npm with scope.

With this behavior sending @scope/package-name in npm and using local dependencies in Rush is still possible ?

**Comment by halfnibble** [comment] 2019-10-26 18:07
My repros are not so insightful after all. It turns out that `rush add -p projectb` worked because "projectb" is [in the npm registry](https://www.npmjs.com/package/projectb). (Thank you @Claudiazhaoya for discovering this).

@VincentSurelle about not reinstalling packages from npm, if your local projects are in the `rush.json` config file, and the versions can be satisfied by the local project, then Rush will symlink your local project automatically. The problem, that you reported on in issue #991, is that we get an error for unpublished projects.

In fact, I think this issue is a duplicate of #991. Therefore, I am closing it in favor of #991, which has more accurate information. Please reopen if you think this is incorrect.

**Closed by halfnibble** 2019-10-26 18:07 UTC
Labels: bug, effort: easy, help wanted

**Comment by dtinth** [comment] 2021-10-14 10:19
The key part is **versions can be satisfied by the local project**.

In my case,

- cli/package.json

  ```js
  { "name": "@my/cli", "dependencies": { "@my/lib": "*" } }
  ```

- lib/package.json

  ```js
  // ❌ Does not work; missing version
  { "name": "@my/lib" }

  // ❌ Does not work; prereleases are not selectable by "*"
  { "name": "@my/lib", "version": "0.1.0-0" }

  // ✅ Works
  { "name": "@my/lib", "version": "0.1.0" }
  ```
