### ISSUE TITLE
[heft] No `--clean` in watch mode?

### ISSUE THREAD

**Issue by Faithfinder** [microsoft/rushstack#4228] opened 2023-07-07 00:27 UTC
Seems like the 0.51 release removed `--clean` from watch mode? I think there would still be value in starting from clean slate?

```
$ pnpm heft build --clean
 ---- lifecycle started ---- 
 ---- build started ---- 
[build:clean] Deleted 0 files and 2 folders
[build:typescript] Using TypeScript version 5.0.4
[build:lint] Using ESLint version 8.40.0
 ---- build finished (19.620s) ---- 
 ---- lifecycle finished (19.622s) ---- 
-------------------- Finished (19.623s) --------------------
```

```
$ pnpm heft build-watch --clean
usage: heft build-watch [-h] [-v] [--production] [--locales LOCALE] [--serve]
heft build-watch: error: Unrecognized arguments: --clean.
```

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.56.1 |

**Comment by iclanton** [comment] 2023-07-08 22:19
I agree. @D4N14L - is there a technical reason why `--clean` can't easily run once before watch mode?

**Comment by D4N14L** [comment] 2023-07-08 22:39
The justification for the removal in watch mode is largely because normal runs now execute their clean at the beginning of their respective phase, instead of at the beginning of the command execution. This change was intended to force cleanup to be more specifically scoped to files produced during a phase for better use by the Rush phased command cache (since otherwise it's much easier to cache files produced by separate phases, which may cause incorrect behavior). The downside of this is that cleaning at the start of each phase during watch mode would cause the watcher to pick up a lot of events that are otherwise just noise. As a substitute, the `heft clean` command can be used to start from a clean slate.

However, it's worth exploring other options to bring this back. A couple thoughts:
- We could re-introduce the `--clean` flag and perform a full clean of every phase before kicking off the watcher. This would essentially bring back the legacy behavior of Heft (but only when in watch mode). This could be a little confusing, but if it's documented then I think it's justified for the additional functionality
- The mentioned limitation may no longer be an issue with the extensive re-write of the watch mode done by @dmichon-msft, and we may be able to simply re-enable the `--clean` flag to behave as it normally does during a non-watch mode Heft run

Thoughts?

**Comment by Faithfinder** [comment] 2023-07-09 17:55
Sounds like first option is easy to do now, and potentially replace with the second when that's on the table? I wouldn't want to wait for an unspecified period of time for the second one, it might take another year.

I guess I can also do `heft clean && heft start` in the meantime

**Comment by D4N14L** [comment] 2023-07-10 19:43
I spoke with @dmichon-msft and he said there should be nothing that prevents the clean from being run during watch mode, other than that it will add a bunch of events that would otherwise get ignored. I'll make a PR to enable the `--clean` flag (only for the first run, though, after which everything will be incremental)

**Closed** 2023-07-12 21:40 UTC
