### ISSUE TITLE
[rush] Enable "rush update" to link to a subfolder with a generated package.json

### ISSUE THREAD

**Issue by arielshaqed** [microsoft/rushstack#1416] opened 2019-07-25 11:16 UTC
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [X] Feature
- [ ] Bug

**Please describe the actual behavior.**

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

I would like to generate an additional package from source files inside the Rush tree to another package inside that tree using an external tool.  Rush should handle rebuilding and linking the package, and possibly changes and publication too.

**What is the expected behavior?**

Our tool [Concord](https://www.npmjs.com/package/concord) generates client and server stubs for Typescript-based RPC.  The tool reads Typescript and generates an NPM package. E.g. running
```
npx concord node  --client fetch shiftjs-interfaces-fetch-client@0.0.1 src/index.ts  -o gen-client
```
generates package code, including a `package.json`, in directory `gen-client`.  Our multi-repo flow is to publish this package and consume it in other repos using `package.lock`.

I would like to use such generated code inside a monorepo project driven by Rush.  Ideally I would have source-controlled packages `a` and `b` inside my repo.  Running `npm run codegen` inside `a` generates a new directory `a/gen` (or a top-level directory `gen`) that contains a package `a-gen`.

Package `b` has `a/gen` as a dependency, and has a preinstall to execute `npm run codegen` inside `a`.

Running `rush update` should rebuild the `a/gen` from `a`, and relink `b` to the generated `a/gen` if versions align.

I would like to do this by adding this or a similar stanza to `rush.json` under `projects`:

```json
{
    "packageName": "a-gen",
    "projectFolder": "a/gen",
    "shouldPublish": true,
    "generatedFromPackage": "a"
}
```

The flag `generated` indicates that `a-gen` is generated as part of installation of another package (in this case `a`), and might not be necessary.  It allows `rush update` to proceed even though `a/gen` does not exist, or exists but with a soon-to-be-replaced `package.json`.

Thanks!

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by octogonz** [comment] 2021-03-19 18:21
Closing, since this seems to be a duplicate of https://github.com/microsoft/rushstack/issues/728

**Closed by octogonz** 2021-03-19 18:21 UTC
