### ISSUE TITLE
[rush] "rush init" generates files with windows newlines (CRLF) on MacOS

### ISSUE THREAD

**Issue by kiprobinsonknack** [microsoft/rushstack#3095] opened 2021-12-15 20:02 UTC
## Summary

Running `rush init` in an empty directory on MacOS results in all generated files using Windows newlines (CRLF)

## Repro steps
1. Be on MacOS (or presumably \*nix would have the same issue)
2. Run `rush init`
3. Look at the generated files. They all use windows newlines:
  - `rush.json`
  - `.gitattributes`
  - `.gitignore`
  - `common/*`

  **Expected result:** These files should use Unix style newlines (i.e. `\n`)

  **Actual result:** These files use Windows style newlines (i.e. `\r\n`)

## Details
n/a

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.57.1 |
| `rushVersion` from rush.json? | **n/a** _(issue is with the script that generates rush.json)_  |
| `useWorkspaces` from rush.json? | **n/a** _(issue is with the script that generates rush.json)_ |
| Operating system? | MacOS 12.1 |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 14.18.1 |

**Comment by iclanton** [comment] 2021-12-16 19:21
Related to/duplicate of https://github.com/microsoft/rushstack/issues/1467

Now Windows OOB tools support LF, we should clean up the `.gitattributes` to remove the CRLF from everything except perhaps `.cmd` files.

**Closed** 2022-01-03 20:53 UTC
