### ISSUE TITLE
[rush] Rush rebuild no longer configurable via command-line.json

### ISSUE THREAD

**Issue by JasonGore** [microsoft/rushstack#1783] opened 2020-03-16 22:20 UTC
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

When updating from Rush 5.11 to 5.21, we noticed that `rush rebuild` started executing `build` commands rather than `rebuild` commands locally. 

We have this entry in `command-line.json`:
```
    {
      "commandKind": "bulk",
      "name": "rebuild",
      "summary": "Clean and rebuild the entire set of projects.",
      "description": "This command assumes that the package.json for each project contains a `scripts` entry for `npm run rebuild` that performs a full clean build.",
      "enableParallelism": true,
      "ignoreMissingScript": false
    },
```

I confirmed in two different repos that this behavior appears to have regression with v5.21 and appears to work fine when switching back to v5.18

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Ian made a [minimal repro](https://github.com/iclanton/rush-testrepo-separate-build-command) as well. (Thanks Ian!)

**What is the expected behavior?**

`rush rebuild` does not run `build` if defined in `command-line.json`.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** Rush
* **Tool Version:** 5.21
* **Node Version:** 10.16.3
  * **Is this a LTS version?** Y
  * **Have you tested on a LTS version?** 
* **OS:** Windows

**Comment by iclanton** [comment] 2020-03-16 22:35
I think we have a bit of a conflict in our design here. The original design for `build` was to behave exactly the same way `rebuild` behaves, but incremental.

But now we allow some parts of that behavior to be modified in `command-line.json`, and we allowed changing the script that was run for `rebuild` until [this change](https://github.com/microsoft/rushstack/pull/1485) sets it back to `"build"` statically.

So how do we fix this? Maybe we should expose the `commandToRun` option in `command-line.json`, separate from the command's name [here](https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/cli/RushCommandLineParser.ts#L236)?

**Comment by octogonz** [comment] 2020-03-16 22:40
Why doesn't this logic work?
```ts
      case RushConstants.bulkCommandKind:
        this.addAction(new BulkScriptAction({
          actionName: command.name,

          // The rush rebuild and rush build command invoke the same NPM script because they share the same
          // package-deps-hash state.
          commandToRun: command.name === RushConstants.rebuildCommandName ? 'build' : undefined,
```

**Comment by octogonz** [comment] 2020-03-16 22:44
> So how do we fix this? Maybe we should expose the `commandToRun` option in `command-line.json`, separate from the command's name [here](https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/cli/RushCommandLineParser.ts#L236)?

This is a potentially confusing design change.  It introduces a fundamental separation between `command.name` vs `commandToRun` that did not exist in the original design.

It is interesting to consider feature improvements:
- Allowing other any command to be incremental and cleanable like `build`/`rebuild` (but is the `re` prefix the best pattern for specifying that?)
- Allowing Rush commands that act as macros for `package.json` scripts

But I would want to think carefully about the design. I would not want to simply expose a program variable in the .json file without considering what specific problems we're trying to solve and what are the design alternatives.

**Comment by iclanton** [comment] 2020-03-16 23:02
>Why doesn't this logic work?

The issue is that if a command called `rebuild` is defined in `command-line.json`, it always runs the `build` script in projects' `package.json`s. Some repo maintainers want it to run a `rebuild` script instead.

>Allowing other any command to be incremental and cleanable like `build`/`rebuild` (but is the re prefix the best pattern for specifying that?)

I wouldn't want to automatically create a `re`- name for every command. Maybe we a allow name for an incrementalized version of commands to be specified? But that opens us up to x-ized versions of every command as well, which will get complicated.

>Allowing Rush commands that act as macros for invoking a single `package.json` script with different parameterizations

That's an interesting approach. One that I kinda like. A commands name is the thing you type on the command-line, and it will run some `package.json` script (which might not have the same name) with some set of parameters. I could see it being useful for repo maintainers to say running `rebuild` is non-incremental, and also includes a `--clean` parameter. Or - maybe even more interestingly, build this into @D4N14L's PR (https://github.com/microsoft/rushstack/pull/1777). You could envision a command running the `clean` script, and then the `build` script and then the `test` script, and only blocking the individual scripts on dependent projects (i.e. - project `B` depends on project `A`, project `B` can have its `clean` script run while project `A` is running its `build` script, immediately after `A` has run its own `clean` script).

**Comment by darsi-an** [comment] 2020-03-17 20:07
> The issue is that if a command called `rebuild` is defined in `command-line.json`, it always runs the `build` script in projects' `package.json`s. 

I see. @iclanton I'll take a look at this over the weekend.

**Comment by christiango** [comment] 2020-04-06 17:32
Hey is this being actively looked at? This is blocking some of the bigger repos in the office org from moving to the latest version of rush. We depend on the ability to have a custom rebuild command that runs clean before build and not running clean for regular build. This lets us leverage incremental TS compilation via project references.

**Comment by iclanton** [comment] 2020-04-11 01:03
This should restore the previous behavior: https://github.com/microsoft/rushstack/pull/1825

I think this change is safe, given that it's restoring some previous behavior, even though that previous behavior wasn't explicitly intentional.

@octogonz, @apostolisms - thoughts?

**Comment by christiango** [comment] 2020-04-11 02:18
I think it was intentional behavior: https://github.com/microsoft/rushstack/pull/1062. We certainly depend on this behavior

**Comment by iclanton** [comment] 2020-04-15 20:50
The fix was released in Rush 5.23.1.

**Closed by iclanton** 2020-04-15 20:50 UTC

**Comment by christiango** [comment] 2020-04-15 20:51
Thanks @iclanton, we'll validate it soon!

**Comment by JasonGore** [comment] 2020-04-15 21:43
It seems to be running our custom `rebuild` commands again, thanks!
