### ISSUE TITLE
[rush] switching away from rush setup breaks npm (changing branch)

### ISSUE THREAD

**Issue by knownasilya** [microsoft/rushstack#2001] opened 2020-07-06 18:50 UTC
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

1. To reproduce checkout https://github.com/Strider-CD/strider/tree/chore/rush
2. `rush install && rush build`
3. Checkout the master branch and cleanup any left over files
4. delete node_modules (and in client-ember/)
5. `yarn install` in toplevel and client-ember/ folders
6. Try `npm publish`

Get this:

```sh
⋊> ~/m/strider on master ◦ npm publish                                                                              11:21:23
npm ERR! path ./common/temp/node_modules/.pnpm/node_modules/babel-plugin-transform-class-property-assignment-to-decorator
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall stat
npm ERR! enoent ENOENT: no such file or directory, stat './common/temp/node_modules/.pnpm/node_modules/babel-plugin-transform-class-property-assignment-to-decorator'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**What is the expected behavior?**

Should run publish or error if not authed.

* **Tool:** rush
* **Tool Version:** 5.27.3
* **Node Version:** 14.5.0
  * **Is this a LTS version?** No
  * **Have you tested on a LTS version?** No
* **OS:** macos latest

**Comment by octogonz** [comment] 2020-07-06 20:29
@knownasilya Can you clarify what "cleanup any left over files" means in step 3?

The problem is clearly caused by a PNPM symlink left over from `rush install`, so how you clean up those symlinks is pretty important.  Generally it should be sufficient to do:

```shell
# Delete the symlinked node_modules folders under each Rush project
$ rush unlink
# Optionally, you can also delete the files under common/temp
$ rush purge
```

**Comment by octogonz** [comment] 2020-07-06 20:33
> 5\. `yarn install` in toplevel and client-ember/ folders

Here you are trying to use a different package manager and build orchestrator in the same folder where Rush was previously used. It is generally not possible or expected for Rush to facilitate this automatically, because Rush has no way of anticipating that you will do this.  Similarly, Yarn is going to leave behind a hoisted `node_modules` folder that will interfere with Rush's [phantom dependency](https://rushjs.io/pages/advanced/phantom_deps/) guarantees.  But Yarn does not provide an automatic way to clean that up, nor can it reasonably be expected to.

Switching between orchestrators is possible if you implement the cleanup yourself (or simply run your CI on a clean VM), but it's generally not a recommended practice.  You should be able to accomplish everything you need with Rush.

**Comment by knownasilya** [comment] 2020-07-07 02:56
The use case is migrating to rush. One branch is the migration while the other is the old code base. I wanted to switch back to the old codebase to release a hotfix (since the migration was still wip) and ran into this issue. I didn't do purge or unlink before switching branches.

**Comment by knownasilya** [comment] 2020-07-07 21:45
So `rush unlink` and `rush purge` did work. This might be worth documenting in the faq, with an example of the error and what to do.

**Comment by octogonz** [comment] 2020-07-07 22:37
@knownasilya Good suggestion. Fixed in https://github.com/microsoft/rushjs.io-website/commit/b8d242b4721293294acccb01f8cbd5dba39fe6f9

**Closed by octogonz** 2020-07-07 22:37 UTC
Labels: needs more info
