### ISSUE TITLE
[rush] neither rush or rushx set `process.env.npm_lifecycle_event`

### ISSUE THREAD

**Issue by jessekrubin** [microsoft/rushstack#3724] opened 2022-10-29 03:25 UTC
rush and rushx should both set `npm_lifecycle_event` env var(s) when exec-ing package-json-scripts/npm-scripts

**Comment by D4N14L** [comment] 2022-11-07 19:19
Duplicate of #3071. If you would like to make a PR to add the change we'd be happy to get that merged!

**Closed by D4N14L** 2022-11-07 19:19 UTC
