### ISSUE TITLE
[rush] Version lifecycle scripts not being run

### ISSUE THREAD

**Issue by DrewBensonTR** [microsoft/rushstack#2438] opened 2021-01-14 19:09 UTC
## Summary

When `rush version` is run, the NPM version lifecycle scripts in package.json (`preversion`, `version`, and `postversion`) are not run.

## Repro steps

1. Add to `package.json`:
```json
  "scripts": {
    "preversion": "echo preversion script",
    "version": "echo version script",
    "postversion": "echo postversionscript"
}
```

2. Run `rush version`

  **Expected result:** 

```sh
$ echo preversion script
preversion script
info New version: 29.6.0
$ echo version script
version script
$ echo postversionscript
postversionscript
```

(Example from `yarn version`, actual output could differ)

  **Actual result:** 

None of the version lifecycle scrips are run

## Details

Pre-version script should run before versioning work starts
Version script should run *after* the version number has been changed and *before* it is committed
Post-version script should run after versioning is complete

## Standard questions

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.35.2 |
| `rushVersion` from rush.json? | 5.35.2 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Windows |
| Would you consider contributing a PR? | Yes, but not soon |
| Node.js version (`node -v`)? | 14.15.1 |

**Comment by halfnibble** [comment] 2021-01-21 19:31
This is a better worded duplicate of #830 

I started on this at one point a while ago, but higher priority work took precedence. Any endeavor to implement this feature would need to take into account our new build caching system. 

Here is the old work in progress PR for reference (although it does not consider the build cache and is not near ready)
https://github.com/microsoft/rushstack/pull/1442/files

Please feel free to contribute a PR if you have time.

**Closed by halfnibble** 2021-01-21 19:31 UTC
