### ISSUE TITLE
[rush] Subdependencies not installed by PNPM

### ISSUE THREAD

**Issue by xpepermint** [microsoft/rushstack#861] opened 2018-10-05 13:29 UTC
The latest version of the PNPM is causing problems on typescript packages that depend on other typescript projects. Typescript definitions are not resolved because some dependencies of the dependencies are simply ignored and not installed. This is very hard to track and I spent 1 day searching for the solution. At the end, I just switched to NPM which works with no problems.

Here's the configuration that might help others:
```
{
  "rushVersion": "5.3.0",
  "npmVersion": "6.4.1",
  "nodeSupportedVersionRange": ">=10.0.0",
}
```

PROPOSAL: Consider setting the NPM as the default option for RushJS (`rush init`).

**Comment by pgonzal** [comment] 2018-10-05 15:56
Could you provide a branch that repros this issue?  I'm not aware of any such problem with PNPM.

**Comment by xpepermint** [comment] 2018-10-05 16:42
Yeah, I'll try to find some time to prepare a repository.

**Comment by halfnibble** [comment] 2019-06-21 08:39
Hello @xpepermint, could you at least tell us which typescript packages caused the issue? I don't think we'll be be switching away from pnpm as the default due to other reasons.

**Comment by xpepermint** [comment] 2019-06-21 16:14
Time flies ... I have this on my to-do :).

**Comment by l3szcz** [comment] 2022-01-14 20:29
I think I encountered a similar issue to the one described. I have a component library package in my `libs` and many project that use that library in `modules` folder.

I recently had the need to upgrade the component library package from ChakraUI v0.x to ChakraUI v1.x and after this upgrade pnpm fails to install all the dependencies of `@chakra-ui/react` package. I switched to `yarn` and all dependencies were properly installed.

I'll try to provide a simple reproduction repo with this issue.

**Comment by l3szcz** [comment] 2022-01-14 20:47
Here's the reproduction:

https://github.com/l3szcz/pnpm-bug-repo

1. If you run `rush update -p --full` with `pnpm` it doesn't download all required packages to `libs/chakra-test/node_modules/@chakra-ui`. The project cannot be built.
1. If you run `rush update -p --full` with `yarn` it downloads all required packages to `libs/chakra-test/node_modules/@chakra-ui` and the `chakra-test` package can be built.

Setting `useWorkspaces` to `true` seems to download all the right packages but it fails with different error:
```
node_modules/.pnpm/core-js-pure@3.20.2/node_modules/core-js-pure: Running postinstall script, done in 57ms
node_modules/.pnpm/core-js@3.20.2/node_modules/core-js: Running postinstall script, done in 41ms
node_modules/.pnpm/fsevents@1.2.13/node_modules/fsevents: Running install script, done in 1s
node_modules/.pnpm/highlight.js@9.18.5/node_modules/highlight.js: Running postinstall script, done in 43ms
node_modules/.pnpm/esbuild@0.14.11/node_modules/esbuild: Running postinstall script, done in 119ms
 ENOENT  ENOENT: no such file or directory, mkdir '/Users/leszcz/Projekty/pnpm-bug-repro/libs/chakra-test/node_modules/.bin'
```

**Comment by elliot-nelson** [comment] 2022-12-21 10:50
With latest Rush, PNPM, and useWorkspaces, all correctly declared dependencies should be installed. (If PNPM does not work and Yarn does, this isn't a sign that PNPM is broken; it's a sign that the dependency itself doesn't correctly declare its own dependencies.)

Closing for now due to age, but please open another ticket if there's a specific package to investigate.

**Closed by elliot-nelson** 2022-12-21 10:50 UTC
Labels: needs more info
