### ISSUE TITLE
[api-extractor] handle merged (augmented) symbols properly

### ISSUE THREAD

**Issue by shlomiassaf** [microsoft/rushstack#1045] opened 2019-01-21 09:00 UTC
When declaration merging is applied on an imported type a new symbol is created (merged symbol).

This symbol contains `SymbolFlags.Transient` [which does not have a matching `AstSymbol`](https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/src/analyzer/AstSymbolTable.ts#L245) which in turn [throws an error](https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/src/analyzer/ExportAnalyzer.ts#L120-L126)

```ts
import { RowContext } from '@angular/cdk/table';
export interface MyExtender extends RowContext<any> {}

declare module '@angular/cdk/table/typings/table.d' {
  interface RowContext<T> {
      myAugmentedProp: string;
  }
}
```

The type itself is fine, it is just a merged type and the transient check should not stop it, for this particular situation.

This is my current workaround, i'm not sure it covers all scenarios:

```ts
import { AstSymbolTable } from '@microsoft/api-extractor/lib/analyzer/AstSymbolTable';

const { _fetchAstSymbol } = AstSymbolTable.prototype as any;

(AstSymbolTable.prototype as any)._fetchAstSymbol = function (followedSymbol, addIfMissing, astImportOptions, localName) {
  let result = _fetchAstSymbol.call(this, followedSymbol, addIfMissing, astImportOptions, localName);

  if (!result && astImportOptions && followedSymbol.flags & ts.SymbolFlags.Transient) {
    followedSymbol.flags = followedSymbol.flags ^ ts.SymbolFlags.Transient;
    result = _fetchAstSymbol.call(this, followedSymbol, addIfMissing, astImportOptions, localName);
    followedSymbol.flags = followedSymbol.flags | ts.SymbolFlags.Transient;
  }

  return result;
};
```

**Comment by pgonzal** [comment] 2019-01-27 20:36
Could you provide a branch with a simple project that repros this error?  I have never encountered transient symbols in any of our projects at work, so I'm pretty unfamiliar with this feature (or why anyone would want it heheh).  Thanks!

**Comment by octogonz** [comment] 2019-02-11 10:59
Does the transient type have the same signature for every source file that references it?  Or does it create a special extended signature that is only visible in the source file that contains the merged declaration? In the latter case, API Extractor would need to somehow distinguish the two different `RowContext` signatures, and have different names for them.

**Comment by octogonz** [comment] 2020-04-25 00:00
Closing, since this is a duplicate of https://github.com/microsoft/rushstack/issues/1709 which has made more progress.

**Closed by octogonz** 2020-04-25 00:00 UTC
Labels: enhancement, needs more info
