### ISSUE TITLE
[api-extractor] @inheritDoc not work as intended in dtsRollup

### ISSUE THREAD

**Issue by k8w** [microsoft/rushstack#2671] opened 2021-05-03 08:42 UTC
## Summary
Expect that `@inheritDoc` tag would automatically copy comment in dtsRollup.
But Actually it keeps `@inheritDoc` in output dts file.

## Repro steps
```ts
/**
 * {@inheritDoc BBB}
 */
export interface AAA {
    
}

/**
 * Something here...
 */
export interface BBB {
    
}
```

  **Expected result:** 
```ts
/**
 * Something here...
 */
export interface AAA {
    
}

/**
 * Something here...
 */
export interface BBB {
    
}
```

  **Actual result:** 
```ts
/**
 * {@inheritDoc BBB}
 */
export interface AAA {
    
}

/**
 * Something here...
 */
export interface BBB {
    
}
```

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? |  |
| Operating system? |  |
| API Extractor scenario? |  |
| Would you consider contributing a PR? |  |
| TypeScript compiler version? |  |
| Node.js version (`node -v`)? |  |

**Comment by tylerbutler** [comment] 2021-09-10 17:52
Possible duplicate of #2062? That issue hasn't been looked at as far as I can tell, though.

**Comment by octogonz** [comment] 2021-09-11 00:01
It's a duplicate. I'll reply to the other issue.

**Closed by octogonz** 2021-09-11 00:01 UTC
