### ISSUE TITLE
[api-extractor-model] ApiTypeAlias do not have members and internal comments.

### ISSUE THREAD

**Issue by fenilli** [microsoft/rushstack#3900] opened 2023-01-17 17:21 UTC
## Summary

Trying to document a exported type with internal members is not possible, as when getting an `ApiNodeKind.TypeAlias` does not get any members attached to it, and comments are also striped.

## Details

If you have an exported type with this signature:

```ts
export declare type FormKitNode = {
    /**
     * Boolean true indicating this object is a valid FormKitNode
     */
    readonly __FKNode__: true;
    /**
     * The internal FormKitContext object — this is not a public API and should
     * never be used outside of the core package itself. It is only here for
     * internal use and as an escape hatch.
     */
    _c: FormKitContext;
    /**
     * Add a child to a node, the node must be a group or list.
     *
     * @public
     */
    add: (node: FormKitNode, index?: number) => FormKitNode;
}
```

The `d.ts` gets the correct output, but when trying to get that using `api-extractor-model` the `ApiTypeAlias` do not have any members ( `__FKNode__`, `_c`, `add` ) attached to it, and when looking at the `Excerpts` it also removes the comments.

I would expect `ApiTypeAlias` work the same way as `ApiInterface` having members of `PropertySignature` and `CallSignature`, with their `TSDocComment`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | ^7.18.4 |
| Operating system? | Linux  |
| API Extractor scenario? | docs (.api.json) |
| Would you consider contributing a PR? | No |
| TypeScript compiler version? | 4.4.3 |
| Node.js version (`node -v`)? | 14.21.1 |

**Comment by octogonz** [comment] 2024-05-13 18:29
This is a duplicate of https://github.com/microsoft/rushstack/issues/3002

**Closed** 2024-05-13 18:29 UTC
