### ISSUE TITLE
[rush] link fails without error message with pnpm 3.x/4.x after mkdirp 1.0.0 release

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/rushstack#1713] opened 2020-01-24 23:18 UTC
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

`rush link` (or the implicit invocation of that from `rush install` fails with no error message:
```
Linking projects together...

LINKING: demoapp
Purging /home/mgl/tmp/rush-busted/demoapp/node_modules
```
(`rush` exits with code `1` at this point)

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

I've made a minimal reproduction repo and published it here: https://github.com/mgabeler-lee-6rs/rush-busted

This repo was created by doing:
* `rm -rf ~/.rush` -- **Important:** see below, this is critical to reproduction if you have a "working" local environment ... you might instead want to move this directory aside instead of deleting it so that you don't get left in the lurch...
* Create & enter a new working directory
* `rush init`
* edit `rush.json` to update the `pnpmVersion`
* `mkdir demoapp && cd demoapp`
* `npm init -y`
* `rush add --exact --dev -p typescript`
* Note: if you don't add any dependencies to the `demoapp`, the bug does not reproduce.  I haven't tried other dependencies besides `typescript` because that was the first thing I added in trying to build a repro similar to our production apps, and that was enough.

The implicit link step from `rush add` reproduces the failure too:
```
Running "pnpm install" in /home/mgl/tmp/rush-busted/common/temp

Using hooks from: /home/mgl/tmp/rush-busted/common/temp/pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
Packages: +1
+
Downloading registry.npmjs.org/typescript/3.7.5: 8.9 MB/8.9 MB, done
Resolving: total 2, reused 0, downloaded 2, done

dependencies:
+ typescript 3.7.5
Updating /home/mgl/tmp/rush-busted/common/config/rush/pnpm-lock.yaml

Linking projects together...

LINKING: demoapp
Purging /home/mgl/tmp/rush-busted/demoapp/node_modules
```

**What is the expected behavior?**

* `rush install` should work
* When things don't work, error messages should be printed
  * Note: `rush link` has no `--debug` flag.  I've tried running e.g. `rush install --debug` and there is no debug output for the period where it's doing the linking.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** `rush` + `pnpm`
* **Tool Version:** Various versions.  Reproducible with rush/pnpm `5.14.0`/`3.8.1` and `5.18.0`/`4.8.0` at least
* **Node Version:** `10.17.0`
  * **Is this a LTS version?** Y
  * **Have you tested on a LTS version?** Y
* **OS:** Linux

----

**Additional notes:**

On my local system, things were _not_ reproducing this bug using `5.14.0`/`3.8.1` until after I purged my `~/.rush` cache, it was only failing in our CI provider (which did not have that cache).  After much great frustration, I tried `rm -rf ~/.rush` on my local system, and the problem started showing up there now too.

The fact that clearing the cache of `rush` & `pnpm` dependencies made this error show up leads me to uspect that some dependency of `rush` has updated in a way that has broken it.  I'm guessing it's a `rush` dependency based on the guess that `rush link` doesn't invoke `pnpm` and thus isn't particularly sensitive to its dependencies?

**Comment by mgabeler-lee-6rs** [comment] 2020-01-24 23:24
I found a coworker who has a working setup.  We compared `npm ls` output of `~/.rush/node-v.../rush-...` directories, and the diff is quite small:
```diff
--- /home/mgl/rush-working.txt	2020-01-24 18:20:28.522475644 -0500
+++ /home/mgl/rush-broken.txt	2020-01-24 18:21:29.226948124 -0500
@@ -26,7 +26,7 @@
   │ ├── @pnpm/types@1.8.0
   │ ├─┬ @types/mz@0.0.32
   │ │ └── @types/node@8.10.54 deduped
-  │ ├── @types/node@10.17.9
+  │ ├── @types/node@10.17.13
   │ ├── @types/ramda@0.25.51
   │ ├─┬ @zkochan/cmd-shim@2.2.4
   │ │ ├── is-windows@1.0.2 deduped
@@ -35,7 +35,7 @@
   │ ├── arr-flatten@1.1.0
   │ ├── is-windows@1.0.2
   │ ├─┬ mkdirp-promise@5.0.1
-  │ │ └── mkdirp@0.5.1 deduped
+  │ │ └── mkdirp@1.0.3
   │ ├─┬ mz@2.7.0
   │ │ ├── any-promise@1.3.0
   │ │ ├── object-assign@4.1.1
@@ -58,7 +58,7 @@
   │   ├── json-parse-better-errors@1.0.2
   │   ├─┬ normalize-package-data@2.5.0
   │   │ ├── hosted-git-info@2.8.5 deduped
-  │   │ ├─┬ resolve@1.13.1
+  │   │ ├─┬ resolve@1.15.0
   │   │ │ └── path-parse@1.0.6
   │   │ ├── semver@5.3.0 deduped
   │   │ └─┬ validate-npm-package-license@3.0.4
@@ -70,7 +70,7 @@
   │   │     └── spdx-license-ids@3.0.5 deduped
   │   └── npm-normalize-package-bin@1.0.1
   ├─┬ @pnpm/logger@1.0.2
-  │ ├── @types/node@10.17.9
+  │ ├── @types/node@10.17.13
   │ ├─┬ bole@3.0.2
   │ │ ├── fast-safe-stringify@1.1.13
   │ │ └── individual@3.0.0
@@ -80,7 +80,7 @@
   │   ├─┬ split2@2.2.0
   │   │ └── through2@2.0.5 deduped
   │   └─┬ through2@2.0.5
-  │     ├─┬ readable-stream@2.3.6
+  │     ├─┬ readable-stream@2.3.7
   │     │ ├── core-util-is@1.0.2
   │     │ ├── inherits@2.0.4 deduped
   │     │ ├── isarray@1.0.0
@@ -140,7 +140,7 @@
   │ ├── mute-stream@0.0.7
   │ ├─┬ run-async@2.3.0
   │ │ └── is-promise@2.1.0
-  │ ├─┬ rxjs@6.5.3
+  │ ├─┬ rxjs@6.5.4
   │ │ └── tslib@1.10.0
   │ ├─┬ string-width@2.1.1
   │ │ ├── is-fullwidth-code-point@2.0.0
```
The update of the `mkdirp` dep of `mkdirp-promise` across a _major version_ is ... suspect?  Esp. since the [upstream changelog](https://github.com/isaacs/node-mkdirp/blob/master/CHANGELOG.md) says `Full rewrite. Essentially a brand new module.`

**Comment by mgabeler-lee-6rs** [comment] 2020-01-24 23:29
On a lark, I checked out `mkdirp-promise` and indeed it has a wildly dangerous `"*"` dependency on `mkdirp`, and `mkdirp` _just_ (3 hours ago ish) published a complete rewrite, which completely breaks 100% of the tests in `mkdirp-promise`

Reported https://github.com/ahmadnassri/mkdirp-promise/issues/87

**Comment by agar23** [comment] 2020-01-24 23:32
seeing the same issue here

**Comment by gregjacobs** [comment] 2020-01-24 23:32
+1. Our CI jobs started failing just about that same time a couple of hours ago.

Rush is broken on our CI, local machines, and docker containers which run our builds

**Comment by mgabeler-lee-6rs** [comment] 2020-01-24 23:41
Ugly workaround: bash one-liner to fix your local environment assuming you have something like `nodenv` in place to handle switching node versions by switching directories.  I ... wouldn't put this in a CI pipeline, unless I was desperate.  WFM, YMMV.

`( set -xeuo pipefail ; for d in $HOME/.rush/node-*/rush-*/ ; do cd $d ; npm i mkdirp@0.5.0 ; done )`

**Comment by bterlson** [comment] 2020-01-25 00:53
Chiming in to say - builds also broken here. Thanks so much @mgabeler-lee-6rs for the investigation!!

**Comment by apostolisms** [comment] 2020-01-25 02:17
We started seeing this issue today too. We're preparing a fix that we're going to release this evening in 5.19.0.

If you can't upgrade to that version, we'll release a patch release for 5.18 and 5.17.

**Comment by iclanton** [comment] 2020-01-25 02:19
https://github.com/microsoft/rushstack/pull/1714 fixes this issue. After this goes in and we validate 5.19, we'll patch previous versions.

**Comment by benjamind** [comment] 2020-01-25 02:20
Thanks so much for the fast response all!

**Comment by iclanton** [comment] 2020-01-25 04:21
Rush 5.19.0 has been released, which has this issue fixed.

**Comment by christopheranderson** [comment] 2020-01-25 04:58
Confirmed. This fixed the issue in botframework's build. Thanks for the quick fix! 🙇‍♂️

**Comment by iclanton** [comment] 2020-01-25 05:35
We found a minor issue in 5.19 after we published it. Please upgrade to 5.19.1 instead.

**Comment by octogonz** [comment] 2020-01-25 05:42
Before we resolve this issue, we now need to fix any affected previous Rush versions, which may be causing CI builds to fail for legacy release branches.  For these scenarios, it's often not feasible to simply "upgrade to the latest version" because:

- There may be a large number of affected branches; OR
- Upgrading may require other expensive upgrades (e.g. a new NodeJS); OR
- Such changes may require careful review and approvals to minimize risk

We found that our exposure to `mkdirp-promise` comes solely from `"@pnpm/link-bins": "~1.0.1"`, which fortunately is a `~` SemVer range.   @iclanton and I believe that if PNPM can publish a patch release (`1.0.4`) for that old major version, pretty much all versions of Rush should pick it up, which should be sufficient to make them start working again.  This would be awesome, since it would be blanket fix that doesn't require anyone to upgrade anything.

I've [posted this proposal](https://gitter.im/pnpm/pnpm?at=5e2bd102dc07667042eb942a) in the PNPM Gitter channel.  Ian's working on a PR now.

**Comment by iclanton** [comment] 2020-01-25 06:21
Here's a PR that would fix `@pnpm/link-bins`: https://github.com/iclanton/link-bins/pull/1

**Comment by octogonz** [comment] 2020-01-25 16:10
🎉 @zkochan has published `@pnpm/link-bins` version 1.0.4 with @iclanton's patch, which should enable older versions of Rush to work again. (Fingers crossed!) 

If your repo folder has a broken install of an older Rush version, you may need to clear the affected node_modules folder and reinstall Rush. Running `rush install --purge` is an easy way to do that.

Everyone please try this fix and report back with any tips or problems. Note that other unrelated NPM packages may also be broken if they relied on `mkdirp-promise`. Hopefully there's not too many of them.

Thanks again @mgabeler-lee-6rs for reporting this and helping investigate! And huge thanks to @iclanton, @zkochan, and the other people who responded quickly and worked to get this incident resolved on a Friday night! 👏

**Comment by mgabeler-lee-6rs** [comment] 2020-01-25 23:46
Thank you for all the fast work by folks to sort this out, esp. on a Friday night :)

> Before we resolve this issue, we now need to ...

I would also kindly ask if a look could be taken towards making the code a bit more protective so that:
> When things don't work, error messages should be printed

In this case we got lucky that just comparing what changed quickly led to the correct answer.  In future situations, we might not be so lucky, and so getting some better error reporting from the portion of rush in question would be beneficial.  Clearly some part of rush knew something went wrong, but didn't report what that was, and the `link` command has no way to ask for `--debug` output.

**Comment by octogonz** [comment] 2020-01-26 00:14
Well, the first step we will take going forward will be to lock down the indirect dependencies of `rush-lib` to make it impossible to install a different set of versions than what was originally tested during release. This can be done by bundling the dependencies or by using a mechanism like `package-lock.json`. By itself, that safeguard would have prevented this incident. We probably should have implemented that a long time ago (given Rush's emphasis on deterministic builds), but this is actually the first time it's ever caused a problem. Generally the Rush team has been very careful to only accept mature, reliable dependences. In this case `mkdirp-promise` came in via an indirect dependency of a reputable library.

As you say, we should also investigate why the error didn't include a more informative message or callstack. Maybe there is a general way to improve that. But in this case an NPM package was effectively substituted with a completely different API contact, which is unlikely to produce an intelligible error message.

**Comment by benjamind** [comment] 2020-01-27 17:59
Confirmed that our builds have now resolved themselves without any further changes on our part. 

Definitely would +1 doing the work to get a reproducible set of dependencies to avoid a repeat of this in the future.

Thanks all for the fast response on this, really had us scratching our heads on Friday!

**Comment by iclanton** [comment] 2020-01-29 07:18
Seems like things are healthy again, so I'm going to close this issue.

**Closed by iclanton** 2020-01-29 07:18 UTC
