### ISSUE TITLE
[rush] rush-pnpm patch-commit fails on `TypeError: isEqual is not a function`

### ISSUE THREAD

**Issue by UberMouse** [microsoft/rushstack#4155] opened 2023-06-02 04:35 UTC
## Summary

Trying to commit a new patch with PNPM and `rush-pnpm path-commit /path/to/modifed/package` is failing with `TypeError: isEqual is not a function`

## Repro steps

1. `rush-pnpm patch <package>`
2. Modify package at path pnpm outputs
3. `rush-pnpm patch-commit /path/to/modified/package`
4. :boom: 

  **Expected result:** Patch is committed

  **Actual result:** Exception
TypeError: isEqual is not a function                                                                                                                        
    at RushPnpmCommandLineParser._postExecuteAsync (/home/taylor/.rush/node-v18.16.0/rush-5.98.0/node_modules/@microsoft/rush-lib/dist/commons.js:5318:22)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                           
    at async RushPnpmCommandLineParser.executeAsync (/home/taylor/.rush/node-v18.16.0/rush-5.98.0/node_modules/@microsoft/rush-lib/dist/commons.js:5133:13) 

## Details

I "fixed" it locally by replacing this call to `isEqual` with `true` because I know that is what it should be returning. If I log `isEqual` it is undefined
https://github.com/microsoft/rushstack/blob/256f208c8dbf8afa9a1fe39a455af8ed5e0e8211/libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts#L406-L407

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.97.1 |
| `rushVersion` from rush.json? | 5.98.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | Linux |
| Would you consider contributing a PR? | No |
| Node.js version (`node -v`)? | 18.16.0 |

**Comment by KraigWalker** [comment] 2023-06-05 12:47
Likely using `pnpm@8`. Duplicate of #4033 – Try with `pnpm@7.x` in your `pnpmVersion`

**Comment by kamontat** [comment] 2023-06-05 14:14
@KraigWalker I have same problem that sure that I use pnpm v7

![CleanShot 2023-06-05 at 21 12 57@2x](https://github.com/microsoft/rushstack/assets/14089557/12d4da85-6656-42bd-b714-8c007c1a90d9)

**Comment by UberMouse** [comment] 2023-06-05 22:33
Can confirm we are also using PNPM 7.x

**Closed** 2023-06-06 22:45 UTC
